insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('814-25-7372', 'Trish Brittoner', 55, '16 Fisk Trail', 'intermediate', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('866-62-4071', 'Rikki Muckloe', 95, '684 Susan Trail', 'advanced', 'Janice Wrettum', false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('228-41-4274', 'Winona Leitche', 23, '815 Burning Wood Pass', 'advanced', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('864-59-0360', 'Craig Usborn', 29, '49 Kinsman Point', 'intermediate', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('233-03-6904', 'Janice Wrettum', 63, '47 Melody Parkway', 'intermediate', 'Rikki Muckloe', false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('205-05-8950', 'Ive Braunfeld', 18, '4 Barnett Street', 'beginner', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('619-60-8868', 'Andreas Ansell', 28, '8531 Nevada Plaza', 'intermediate', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('460-18-9132', 'Inglebert Gianettini', 84, '92 Spohn Alley', 'advanced', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('493-56-8723', 'Allix Rowe', 84, '1549 Barnett Pass', 'advanced', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('539-25-3094', 'Valentine Killshaw', 37, '5 Declaration Point', 'advanced', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('570-76-1770', 'Neysa Whitehorne', 38, '47 Sunbrook Hill', 'advanced', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('760-48-0643', 'Ban Gimert', 92, '93 Thierer Junction', 'advanced', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('873-68-4916', 'Pren Mowles', 40, '66 Clarendon Circle', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('788-76-2768', 'Giacomo Bazeley', 65, '63 Portage Junction', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('325-11-9232', 'Noelyn Sange', 26, '92161 Lien Way', 'advanced', 'Hayley Crosetto', true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('422-18-9198', 'Alix Belly', 95, '15396 Bartillon Park', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('646-04-1469', 'Hayley Crosetto', 20, '725 Sullivan Drive', 'beginner', 'Noelyn Sange', false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('692-14-0486', 'Willie Alan', 93, '06 Anthes Circle', 'advanced', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('152-75-6503', 'Giuditta Bartolomeo', 94, '6310 Ridgeway Crossing', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('473-63-2611', 'Calypso Grzelczyk', 26, '0 Shelley Junction', 'intermediate', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('392-90-6464', 'Katlin Pullman', 30, '55267 Fair Oaks Trail', 'advanced', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('655-06-2415', 'Patty Brinklow', 82, '5 Fremont Drive', 'intermediate', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('458-30-4808', 'Rafaelia Kelsell', 96, '1956 Burning Wood Place', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('846-36-1490', 'Davita Espine', 66, '7442 Golf View Hill', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('727-99-8933', 'Galen Powderham', 26, '9 Mendota Avenue', 'intermediate', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('595-69-7137', 'Marj Ashlin', 25, '77 Reindahl Parkway', 'beginner', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('772-78-2120', 'Trudey Alldread', 74, '6838 Cardinal Pass', 'advanced', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('150-71-1316', 'Livy Pelman', 89, '13586 Merrick Terrace', 'beginner', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('356-58-5592', 'Onofredo Hauch', 47, '247 Kingsford Way', 'advanced', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('600-57-3950', 'Talya Giriardelli', 96, '754 Hooker Parkway', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('786-97-7776', 'Patience Holgan', 43, '7 Londonderry Junction', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('895-40-0492', 'Jeddy Engelbrecht', 41, '6 Manufacturers Drive', 'beginner', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('825-99-6450', 'Cobbie Becraft', 47, '78 Miller Hill', 'intermediate', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('481-33-5039', 'Connie Buzza', 21, '6736 Hagan Trail', 'advanced', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('338-93-6411', 'Randi Bilbey', 75, '28956 Michigan Center', 'intermediate', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('595-33-2080', 'Jose Giacopini', 37, '981 Melrose Alley', 'advanced', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('196-31-4214', 'Catlaina Longman', 100, '6 Kensington Trail', 'intermediate', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('492-88-6471', 'Crosby Martino', 19, '32357 Hoffman Crossing', 'beginner', null, false);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('468-68-5119', 'Bat Waitland', 38, '1 Butternut Place', 'intermediate', null, true);
insert into student (personal_number, name, age, address, skill_level, sibling, is_accepted) values ('585-69-4089', 'Valeda Pitchers', 75, '6 Crescent Oaks Alley', 'beginner', null, true);